// File generated by FlutterFire CLI (manually via Firebase Management API).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions no configurado para esta plataforma.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcRPd6kLU9Qdlg6SPLrm8w_Ae5SsVBUX0',
    appId: '1:850478985075:web:f876979d3e2f6a211c1f06',
    messagingSenderId: '850478985075',
    projectId: 'colis-app-72dfa',
    authDomain: 'colis-app-72dfa.firebaseapp.com',
    storageBucket: 'colis-app-72dfa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-cIy90WfDU6yNCCGAo89TGuy2jn4oMKY',
    appId: '1:850478985075:android:7cfed899fc98c1bf1c1f06',
    messagingSenderId: '850478985075',
    projectId: 'colis-app-72dfa',
    storageBucket: 'colis-app-72dfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5qDKWpD2jnOp4AN6byA8q-Wi41iIDadc',
    appId: '1:850478985075:ios:5a1a69a826f750fd1c1f06',
    messagingSenderId: '850478985075',
    projectId: 'colis-app-72dfa',
    storageBucket: 'colis-app-72dfa.firebasestorage.app',
    iosBundleId: 'com.colis.colisAppMobile',
  );
}
